version: '3.8'

services:
  wings:
    image: ghcr.io/pterodactyl/wings:v1.6.1
    restart: always
    networks:
      - wings0
      - external
    tty: true
    ports:
      - "25600-25610:25600-25610"
    environment:
      TZ: "UTC"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pterodactyl
    volumes:
      - "/data/pterodactyl/wings/var/run/docker.sock:/var/run/docker.sock"
      - "/data/pterodactyl/wings/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/data/pterodactyl/wings/var/lib/pterodactyl/:/var/lib/pterodactyl/"
      - "/data/pterodactyl/wings/etc/pterodactyl/:/etc/pterodactyl/"
      - "./config.yaml:/etc/pterodactyl/config.yml:ro"
      - "/data/pterodactyl/wings/var/log/pterodactyl/:/var/log/pterodactyl/"
      - "/data/pterodactyl/wings/tmp/pterodactyl/:/tmp/pterodactyl/"
      - "/data/pterodactyl/wings/etc/ssl/certs:/etc/ssl/certs:ro"
      # you may need /srv/daemon-data if you are upgrading from an old daemon
      #- "/srv/daemon-data/:/srv/daemon-data/"
      # Required for ssl if you use let's encrypt. uncomment to use.
      #- "/etc/letsencrypt/:/etc/letsencrypt/"
    labels:
      - "traefik.enable=true"
      - "expose-external=true"
      - "traefik.http.routers.pterodactylwing.rule=Host(`node1.pterodactyl.triserden.dev`)"
      - "traefik.http.routers.pterodactylwing.entrypoints=websecure"
      - "traefik.http.routers.pterodactylwing.tls.certresolver=http"
      - "traefik.http.services.pterodactylwing.loadbalancer.server.port=8080"
      - "traefik.docker.network=external"

networks:
  wings0:
    name: wings0
    driver: bridge
    ipam:
      config:
        - subnet: "172.22.0.0/16"
    driver_opts:
      com.docker.network.bridge.name: wings0
  external:
    external: true
