debug: ENC[AES256_GCM,data:Qfq4bwY=,iv:b7d3IqYNPowWzBD79Cu92svObNLJYguhzYxjN9THUA8=,tag:DPSJzHIij8ZmO0dfo8IjBg==,type:bool]
uuid: ENC[AES256_GCM,data:7yTnReRMc5qVvKMTCrzXnX+FHJ72PX77sTk4/Q7kc6utzxCX,iv:x8ze3NlvxiRwDd+ozU1B96WgG2yYFksWrIxSY6PF4LY=,tag:EUCrmqy5g/eFU2O+33r1cg==,type:str]
token_id: ENC[AES256_GCM,data:IFqgpchyzjv83gLT8wO6iQ==,iv:A8InrOGobrR/ao3udlphmbqHbObEW0fXO1Dd5suGYOk=,tag:Ek1dynn+WVMBpjVIc1IGIQ==,type:str]
token: ENC[AES256_GCM,data:jSribvmj5Tvy9lQ+guNVqeJJftmW2Up8L9Y+rsUV5qx8tXdJc2uvVRx9u46QKWdB+ChJWpbzX7AIMddGo0t4nA==,iv:JmFAjVUakbSi5ZazDugFUhIQGjUQ82o1kLUt/n9jy0c=,tag:iqFBEThVdNf4oyqUj0AK2g==,type:str]
api:
    host: ENC[AES256_GCM,data:H9IeVczMaA==,iv:9Qm1cb/3Bve6+BLyfZ+qDSfmTbWfA918rBBi413gm1U=,tag:SFiqJkACWy3xA4pm3Ce+ww==,type:str]
    port: ENC[AES256_GCM,data:3M7YJA==,iv:4elKj5pfMJXJ4v7hiw8TSk77Ha5AgCEalqKcyq88nAY=,tag:i9Kw9eORjuoffJr3dZ7VbQ==,type:int]
    ssl:
        enabled: ENC[AES256_GCM,data:N2lPDpg=,iv:SypjmLyTb9/VUtdosW3k40DoWqBXN0x52e/rdNstV38=,tag:p0jcDD3uH6NAqxYcMBjYXQ==,type:bool]
        cert: ENC[AES256_GCM,data:9IK8PK9aegeDuOBMuIJQ+DblOYF0h5yF/YxfrVR2JHIiTXUeaQZ1OkW1VSKquhgZvuLtW6LJ4rfi9GfkcdiqMqJbwA==,iv:Xe+gtZphpO7u3gFL+gkKWWdsPbXAxxlbFO8tZCbP1eo=,tag:n1r24XdU6xd/DYSRJpdieQ==,type:str]
        key: ENC[AES256_GCM,data:o+qn4m8iOAxsNoxiNuQ8R3CuTMDm8TpehtK0yFxDbes7Gp8CqeCIraHPT8aufj60st3P+HkZVZGVry9Y8rqsWok=,iv:/RpC/0gb3FD5RmDF0DvgGDoGz/FUszVTh2mgsoUS7xY=,tag:pmhH7j+0uwVWl/KxCVJyrg==,type:str]
    upload_limit: ENC[AES256_GCM,data:TIFt,iv:sfE6IckQhPYRVOp/Ey10XN5IUOcPhVPS0QOPa0t9hLQ=,tag:Fwc8msAkMnM2FFXxXLWqVA==,type:int]
system:
    data: ENC[AES256_GCM,data:3P/dRmDUh4ya/cH2wal5QfZ4Uf3YLhv/uVrQ/PltHGoGW3g=,iv:QUmuxDZk+M9MEnn8oPKrUmsleTZUlAMG4l996QrEs6g=,tag:MiMmdXwOlrSXXpbEgC6PNQ==,type:str]
    sftp:
        bind_port: ENC[AES256_GCM,data:AadUgg==,iv:D9LbUJ/9VwbaWDKltGUEZKTiUKODptesWMeFBotBxa4=,tag:x/g7N99NI/2d78IJZoKlqQ==,type:int]
allowed_mounts: []
remote: ENC[AES256_GCM,data:iX+DSoRn6FKugcd5OStN3ocPmSl2V3QT/LSijY63wd7B,iv:y4mvn9pd6604jvM+1Y0h4Lro18iIn0CPgguPtX0ODWM=,tag:iBaFnBrTXJW8tOi06TI/0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15qwcm0rtksf2yqm2wqxawrex49cllp77tuayvn4yq9ufk44l9adsdyzk79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z1NRekNibGJzN203bC81
            eU9SRFEvV1VoTjdqMCtwNEM2TGVFOVoweEdRCmZWTG96SE9GbTM5dGl1WmtrUGM5
            OHRITkR4NDJ4WUJZb1l1dEM5bmtMa0kKLS0tIDR4cllGK3lIQWxnQzlaSkVDL0pu
            ZWNhUHBZeFNWSnFQWGR3THhjRit3S1UKbNiJGUtFUIG3i3ncKlC2xOo0yC4T9/ua
            IzeFPpf+UqUrf8ZP3cE0zavB8AXG/VF4anuOpJaQBVvKeScPtAHMCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-23T00:56:56Z"
    mac: ENC[AES256_GCM,data:xIzrelvm4YP41uN8LJdcFVc8bIuGRJB4q71c9HwQY3KKgIdKI60MmWPnn4DFJQR8MbkBnqlcXuu8t58RoUGxu9pRaSqecfisk2sf6PBTLn1vVd4tF0UOe+4hk2/D5bC9D3o+jvCqGkVNxcF7fbLZzgkcKtHyxHAFsSx6oZ6Gd7k=,iv:UkpMy09Ti225Ssjz9x7dUhbkI7ul7Yh7MdmGSdvUsvM=,tag:GYog/NnW+cSJPV3ADczMfA==,type:str]
    pgp:
        - created_at: "2025-01-08T15:07:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DMGicT/uUkIcSAQdAwNPesPX0LGHI3jAyMonzvnB7zpr03d8U2yPyU32zq0Iw
            lzLWVWF91tZZbTEVPrU4XQuvzTaNC9rOQdKkEzC5082AZKh1mATJf6ljzgnKPIJz
            0l4BE0F85ItiW1w/hAQfwgvO9xMEQGd0BUR7Ed9Clv8zK8EmUZgdgU60L3rq6abb
            O+/1PUrlC/UUsiyhGp+KbVeWFB09nRIRPnuvIJOVIX/RUespLKxF0OkOeTBwY+zK
            =kmIm
            -----END PGP MESSAGE-----
          fp: 2422C7EE03C629FD998BF923FD5CD86B6562D6B7
    unencrypted_suffix: _unencrypted
    version: 3.9.4
