debug: ENC[AES256_GCM,data:Qfq4bwY=,iv:b7d3IqYNPowWzBD79Cu92svObNLJYguhzYxjN9THUA8=,tag:DPSJzHIij8ZmO0dfo8IjBg==,type:bool]
uuid: ENC[AES256_GCM,data:mAfoZm1bNsOQ2wJVGeXGUzYhkczPRDP0rhHbvShLREWQXxZF,iv:4lauBLIzZwimlvJ0nQJl00KZcPvgOCdJqjiFtdAfzcY=,tag:TOtvNLnYUZ5De5Cbp6u8Zw==,type:str]
token_id: ENC[AES256_GCM,data:Rp4WDajgxZ0on9yWAaSEfA==,iv:5Pg6DKFhk71B9IIqfAMJIH3LqwqYrHwvnD2sd9DqFm8=,tag:8aIH39prglV2zWD6kwoHzA==,type:str]
token: ENC[AES256_GCM,data:qcbK4IK23MXTTOC26QTG1KG7Rtt+xhPPlICnejTJ4lKBT0mAeWl/KjQ42SGB+qJkjo8ERwI1FEpNxIjxsopKwg==,iv:58tluPHuBfJOxuFPJ5e3EYbv4XFiSj8wFANHY5CQnC8=,tag:9cb416rizCCqfj/myM5e8g==,type:str]
api:
    host: ENC[AES256_GCM,data:H9IeVczMaA==,iv:9Qm1cb/3Bve6+BLyfZ+qDSfmTbWfA918rBBi413gm1U=,tag:SFiqJkACWy3xA4pm3Ce+ww==,type:str]
    port: ENC[AES256_GCM,data:WRguTQ==,iv:JHqQSud1XEAtmXuuYk81mjqRqrFIRwqIUKCtX8ruRDg=,tag:orsgGFNOVJK8ZRwbqa0PVA==,type:int]
    ssl:
        enabled: ENC[AES256_GCM,data:N2lPDpg=,iv:SypjmLyTb9/VUtdosW3k40DoWqBXN0x52e/rdNstV38=,tag:p0jcDD3uH6NAqxYcMBjYXQ==,type:bool]
        cert: ENC[AES256_GCM,data:nKouJMLRXcu/iYX9MCvFEBd6DkyzAoLbamJlIs9oBMT55QsYDfOPb5uNzCjQqwqxAnE/bHyIATJjcI7RKQ==,iv:Y6CBbOEf+wY3vPRkOnB2zEQGJNc68P0nBxBByJkNEDM=,tag:Iv+GQqz9QRoEa2Ipdd8exw==,type:str]
        key: ENC[AES256_GCM,data:vQf+Ruh/kGq9HrVVRA+S8XiNzHP+QmfPCh8VuW51ar2xeNKRVgWiHXGrY3nlcD3cRWam55LGVS7h3R4=,iv:7Cljq2JH3o0jC+0jJS9hiKJ45eKfxJDoCLGWY3t41dw=,tag:rU3E21XPrlGoQNEBemUffg==,type:str]
    upload_limit: ENC[AES256_GCM,data:TIFt,iv:sfE6IckQhPYRVOp/Ey10XN5IUOcPhVPS0QOPa0t9hLQ=,tag:Fwc8msAkMnM2FFXxXLWqVA==,type:int]
system:
    data: ENC[AES256_GCM,data:kb3DhSRivoKtnpxTFgi2jd3OssnFJ8qu1W04rg==,iv:pWlIgUltHdAHUXDc6SQIVHGSxvrqdu5DF3Kek0dkOl4=,tag:TBvthOUMNdd02XiL6qrvXA==,type:str]
    sftp:
        bind_port: ENC[AES256_GCM,data:B+XpWQ==,iv:qclzhGDjuTPf1NGXIcJDj+/89ap5A5Jle/rgdlKdT90=,tag:ntUSjnR25b/Cesb99TwJNg==,type:int]
allowed_mounts: []
remote: ENC[AES256_GCM,data:Pts4pRP6EWHwJDPghTeoJ2a2dTLotBTzpTaV,iv:qYbLNSs5zbuy3dIQxMiCWWfHEtsd/R5ZaIwEwrguFes=,tag:Q4sm/LcipSh+uIH3iE9Tag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15qwcm0rtksf2yqm2wqxawrex49cllp77tuayvn4yq9ufk44l9adsdyzk79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z1NRekNibGJzN203bC81
            eU9SRFEvV1VoTjdqMCtwNEM2TGVFOVoweEdRCmZWTG96SE9GbTM5dGl1WmtrUGM5
            OHRITkR4NDJ4WUJZb1l1dEM5bmtMa0kKLS0tIDR4cllGK3lIQWxnQzlaSkVDL0pu
            ZWNhUHBZeFNWSnFQWGR3THhjRit3S1UKbNiJGUtFUIG3i3ncKlC2xOo0yC4T9/ua
            IzeFPpf+UqUrf8ZP3cE0zavB8AXG/VF4anuOpJaQBVvKeScPtAHMCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-09T13:02:08Z"
    mac: ENC[AES256_GCM,data:qoaQV9UKtd/dfqaJVCs00qdd1AD4M+fq4naDiRZcwKdJ5VJ/UF+f2VDr1M2YbmuM9mkxhs6ZwjQ1VVIzIdkkX86XoLFRj2WRzFUxAmYcjC8RAV33ApH8IcNQnWmBe2yWwd2Up4GVgJldecTmAumdd9wksIuBAPQzaZ3GQUkXBbQ=,iv:HWNK0crZRlS/YHIWCZfqCbwvNBFP0Ihd7RqOPpUmjqU=,tag:xlbhRmwDb6w8ILmynd59GQ==,type:str]
    pgp:
        - created_at: "2025-01-08T15:07:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DMGicT/uUkIcSAQdAwNPesPX0LGHI3jAyMonzvnB7zpr03d8U2yPyU32zq0Iw
            lzLWVWF91tZZbTEVPrU4XQuvzTaNC9rOQdKkEzC5082AZKh1mATJf6ljzgnKPIJz
            0l4BE0F85ItiW1w/hAQfwgvO9xMEQGd0BUR7Ed9Clv8zK8EmUZgdgU60L3rq6abb
            O+/1PUrlC/UUsiyhGp+KbVeWFB09nRIRPnuvIJOVIX/RUespLKxF0OkOeTBwY+zK
            =kmIm
            -----END PGP MESSAGE-----
          fp: 2422C7EE03C629FD998BF923FD5CD86B6562D6B7
    unencrypted_suffix: _unencrypted
    version: 3.9.2
