# Auto-generated by compose2nix.

{ pkgs, config, inputs, lib, ... }:

let secretsFolder = builtins.toString inputs.secrets;
in {
  sops.secrets."services/hoarder.env" = {
    sopsFile =
      "${secretsFolder}/sops/${config.host.hostname}/services/hoarder.env";
    format = "dotenv";
  };
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."hoarder-chrome" = {
    image = "gcr.io/zenika-hub/alpine-chrome:123";
    cmd = [
      "--no-sandbox"
      "--disable-gpu"
      "--disable-dev-shm-usage"
      "--remote-debugging-address=0.0.0.0"
      "--remote-debugging-port=9222"
      "--hide-scrollbars"
    ];
    log-driver = "journald";
    environmentFiles = [ config.sops.secrets."services/hoarder.env".path ];
    extraOptions = [ "--network-alias=chrome" "--network=internal" ];
  };
  systemd.services."docker-hoarder-chrome" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-hoarder-root.target" ];
    wantedBy = [ "docker-compose-hoarder-root.target" ];
  };
  virtualisation.oci-containers.containers."hoarder-meilisearch" = {
    image = "getmeili/meilisearch:v1.11.1";
    environment = { "MEILI_NO_ANALYTICS" = "true"; };
    volumes = [ "/data/hoarder/meilisearch:/meili_data:rw" ];
    log-driver = "journald";
    environmentFiles = [ config.sops.secrets."services/hoarder.env".path ];
    extraOptions = [ "--network-alias=meilisearch" "--network=internal" ];
  };
  systemd.services."docker-hoarder-meilisearch" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-hoarder-root.target" ];
    wantedBy = [ "docker-compose-hoarder-root.target" ];
  };
  virtualisation.oci-containers.containers."hoarder-web" = {
    image = "ghcr.io/hoarder-app/hoarder:release";
    environment = {
      "BROWSER_WEB_URL" = "http://chrome:9222";
      "DATA_DIR" = "/data";
      "MEILI_ADDR" = "http://meilisearch:7700";
    };
    volumes = [ "/data/hoarder/data:/data:rw" ];
    ports = [ "3000:3000/tcp" ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.hoarder.entrypoints" = "websecure";
      "traefik.http.routers.hoarder.rule" =
        "Host(`hoarder.local.triserden.dev`)";
      "traefik.http.routers.hoarder.tls" = "true";
      "traefik.http.routers.hoarder.tls.certresolver" = "cloudflare";
      "traefik.http.services.hoarder.loadbalancer.server.port" = "3000";
    };
    log-driver = "journald";
    extraOptions = [ "--network-alias=web" "--network=internal" ];
  };
  systemd.services."docker-hoarder-web" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-hoarder-root.target" ];
    wantedBy = [ "docker-compose-hoarder-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-hoarder-root" = {
    unitConfig = { Description = "Root target generated by compose2nix."; };
    wantedBy = [ "multi-user.target" ];
  };
}
