# Auto-generated by compose2nix.

{ pkgs, config, inputs, lib, ... }:

let secretsFolder = builtins.toString inputs.secrets;
in {
  sops.secrets."services/paperless.env" = {
    sopsFile =
      "${secretsFolder}/sops/${config.host.hostname}/services/paperless.env";
    format = "dotenv";
  };
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."paperless-broker" = {
    image = "docker.io/library/redis:7";
    volumes = [ "/data/paperless/redisdata:/data:rw" ];
    log-driver = "journald";
    extraOptions = [ "--network-alias=broker" "--network=internal" ];
  };
  systemd.services."docker-paperless-broker" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-paperless-root.target" ];
    wantedBy = [ "docker-compose-paperless-root.target" ];
  };
  virtualisation.oci-containers.containers."paperless-db" = {
    image = "docker.io/library/postgres:16";
    environment = {
      "POSTGRES_DB" = "paperless";
      "POSTGRES_PASSWORD" = "paperless";
      "POSTGRES_USER" = "paperless";
    };
    volumes = [ "/data/paperless/pgdata:/var/lib/postgresql/data:rw" ];
    log-driver = "journald";
    extraOptions = [ "--network-alias=db" "--network=internal" ];
  };
  systemd.services."docker-paperless-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-paperless-root.target" ];
    wantedBy = [ "docker-compose-paperless-root.target" ];
  };
  virtualisation.oci-containers.containers."paperless-gotenberg" = {
    image = "docker.io/gotenberg/gotenberg:8.7";
    cmd = [
      "gotenberg"
      "--chromium-disable-javascript=true"
      "--chromium-allow-list=file:///tmp/.*"
    ];
    log-driver = "journald";
    extraOptions = [ "--network-alias=gotenberg" "--network=internal" ];
  };
  systemd.services."docker-paperless-gotenberg" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-paperless-root.target" ];
    wantedBy = [ "docker-compose-paperless-root.target" ];
  };
  virtualisation.oci-containers.containers."paperless-tika" = {
    image = "docker.io/apache/tika:latest";
    log-driver = "journald";
    extraOptions = [ "--network-alias=tika" "--network=internal" ];
  };
  systemd.services."docker-paperless-tika" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-paperless-root.target" ];
    wantedBy = [ "docker-compose-paperless-root.target" ];
  };
  virtualisation.oci-containers.containers."paperless-webserver" = {
    image = "ghcr.io/paperless-ngx/paperless-ngx:latest";
    environment = {
      "PAPERLESS_DBHOST" = "db";
      "PAPERLESS_REDIS" = "redis://broker:6379";
      "PAPERLESS_TIKA_ENABLED" = "1";
      "PAPERLESS_TIKA_ENDPOINT" = "http://tika:9998";
      "PAPERLESS_TIKA_GOTENBERG_ENDPOINT" = "http://gotenberg:3000";
    };
    volumes = [
      "/data/paperless/data:/usr/src/paperless/data:rw"
      "/data/paperless/media:/usr/src/paperless/media:rw"
      "/home/triserden/.dotfiles/hosts/mai/services/compose-files/consume:/usr/src/paperless/consume:rw"
      "/home/triserden/.dotfiles/hosts/mai/services/compose-files/export:/usr/src/paperless/export:rw"
    ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.paperless.entrypoints" = "websecure";
      "traefik.http.routers.paperless.rule" =
        "Host(`paperless.local.triserden.dev`)";
      "traefik.http.routers.paperless.tls.certresolver" = "cloudflare";
      "traefik.http.services.paperless.loadbalancer.server.port" = "8000";
    };
    dependsOn = [
      "paperless-broker"
      "paperless-db"
      "paperless-gotenberg"
      "paperless-tika"
    ];
    log-driver = "journald";
    environmentFiles = [ config.sops.secrets."services/paperless.env".path ];
    extraOptions = [ "--network-alias=webserver" "--network=internal" ];
  };
  systemd.services."docker-paperless-webserver" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-paperless-root.target" ];
    wantedBy = [ "docker-compose-paperless-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-paperless-root" = {
    unitConfig = { Description = "Root target generated by compose2nix."; };
    wantedBy = [ "multi-user.target" ];
  };
}
