keys:
  - &triserden 2422C7EE03C629FD998BF923FD5CD86B6562D6B7
  - &futaba age15qwcm0rtksf2yqm2wqxawrex49cllp77tuayvn4yq9ufk44l9adsdyzk79
  - &megumi age1rldtavqum7mtsvd5zjkafdlvc4tw5j735x2tnpy22znad2jgm9fsuvhxay

creation_rules:
  - path_regex: hosts/megumi/secrets.yaml$
    key_groups:
      - pgp:
          - *triserden
        age:
          - *megumi
  - path_regex: hosts/futaba/secrets.yaml$
    key_groups:
      - pgp:
          - *triserden
        age:
          - *futaba



