keys:
  - &triserden 2422C7EE03C629FD998BF923FD5CD86B6562D6B7

    # Note: These 2 have temp keys until they are fully deployed
  - &yuki age1rldtavqum7mtsvd5zjkafdlvc4tw5j735x2tnpy22znad2jgm9fsuvhxay
  - &futaba age1v3jwkwxk5sd3ahs0qsypu92lwc8qhlzaufp372ds03u40zxwr5nqjw69lz

creation_rules:
  - path_regex: hosts/yuki/id_ed25519$
    key_groups:
      - pgp:
          - *triserden
        age:
          - *yuki
  - path_regex: hosts/yuki/secrets.yaml$
    key_groups:
      - pgp:
          - *triserden
        age:
          - *yuki
  - path_regex: hosts/futaba/id_ed25519$
    key_groups:
      - pgp:
          - *triserden
        age:
          - *futaba
  - path_regex: hosts/futaba/secrets.yaml$
    key_groups:
      - pgp:
          - *triserden
        age:
          - *futaba



