# Auto-generated by compose2nix.

{ inputs, config, lib, ... }:

let secretsFolder = builtins.toString inputs.secrets;
in {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  sops.secrets = {
    "services/firefly3.env" = {
      sopsFile =
        "${secretsFolder}/sops/${config.host.hostname}/services/firefly3.env";
      format = "dotenv";
    };
    "services/firefly3importer.env" = {
      sopsFile =
        "${secretsFolder}/sops/${config.host.hostname}/services/firefly3importer.env";
      format = "dotenv";
    };
    "services/firefly3database.env" = {
      sopsFile =
        "${secretsFolder}/sops/${config.host.hostname}/services/firefly3database.env";
      format = "dotenv";
    };
  };

  # Containers
  virtualisation.oci-containers.containers."firefly_iii_core" = {
    image = "fireflyiii/core:version-6.5.8";
    volumes =
      [ "/data/firefly3/firefly_iii_upload:/var/www/html/storage/upload:rw" ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.firefly3.entrypoints" = "websecure";
      "traefik.http.routers.firefly3.rule" =
        "Host(`firefly3.local.triserden.dev`)";
      "traefik.http.routers.firefly3.tls.certresolver" = "cloudflare";
      "traefik.http.services.firefly3.loadbalancer.server.port" = "8080";
    };
    environmentFiles = [ config.sops.secrets."services/firefly3.env".path ];
    dependsOn = [ "firefly_iii_db" ];
    log-driver = "journald";
    extraOptions =
      [ "--hostname=app" "--network-alias=app" "--network=internal" ];
  };
  systemd.services."docker-firefly_iii_core" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-firefly3-root.target" ];
    wantedBy = [ "docker-compose-firefly3-root.target" ];
  };
  virtualisation.oci-containers.containers."firefly_iii_cron" = {
    image = "alpine";
    cmd = [
      "sh"
      "-c"
      ''
        echo "0 3 * * * wget -qO- http://app:8080/api/v1/cron/qhVIM2943RYIhfhxklDhWxi4BSkJA1U8" | crontab - && crond -f -L /dev/stdout''
    ];
    log-driver = "journald";
    extraOptions = [ "--network-alias=cron" "--network=internal" ];
  };
  systemd.services."docker-firefly_iii_cron" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-firefly3-root.target" ];
    wantedBy = [ "docker-compose-firefly3-root.target" ];
  };
  virtualisation.oci-containers.containers."firefly_iii_db" = {
    image = "mariadb:lts";
    volumes = [ "/data/firefly3/firefly_iii_db:/var/lib/mysql:rw" ];
    log-driver = "journald";
    environmentFiles =
      [ config.sops.secrets."services/firefly3database.env".path ];
    extraOptions =
      [ "--hostname=db" "--network-alias=db" "--network=internal" ];
  };
  systemd.services."docker-firefly_iii_db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-firefly3-root.target" ];
    wantedBy = [ "docker-compose-firefly3-root.target" ];
  };
  virtualisation.oci-containers.containers."firefly_iii_importer" = {
    image = "fireflyiii/data-importer@sha256:9d2d375550286dcd1696922c2684eeee85c7b5b2e729478be57f55bf03c76a88";
    labels = {
      "traefik.enable" = "true";
      "traefik.http.routers.fireflyimporter.entrypoints" = "websecure";
      "traefik.http.routers.fireflyimporter.rule" =
        "Host(`fireflyimporter.local.triserden.dev`)";
      "traefik.http.routers.fireflyimporter.tls.certresolver" = "cloudflare";
      "traefik.http.services.fireflyimporter.loadbalancer.server.port" = "8080";
    };
    environmentFiles =
      [ config.sops.secrets."services/firefly3importer.env".path ];
    dependsOn = [ "firefly_iii_core" ];
    log-driver = "journald";
    extraOptions =
      [ "--hostname=importer" "--network-alias=importer" "--network=internal" ];
  };
  systemd.services."docker-firefly_iii_importer" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-firefly3-root.target" ];
    wantedBy = [ "docker-compose-firefly3-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-firefly3-root" = {
    unitConfig = { Description = "Root target generated by compose2nix."; };
    wantedBy = [ "multi-user.target" ];
  };
}
