version: '2'
services:
  daemon:
    environment:
      - TZ="Europe/Amsterdam"
    image: ccarney16/pterodactyl-daemon:latest
    ports:
      - 2022:2022
    restart: unless-stopped
    volumes:
      - /data/hlresortrvar/lib/pterodactyl:/var/lib/pterodactyl
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/pterodactyl/:/tmp/pterodactyl/:Z
      - /data/hlresort/conf.d/daemon:/etc/pterodactyl:Z
      - /data/hlresort/conf.d/letsencrypt:/etc/letsencrypt:ro
      - /data/hlresort/conf.d/certs:/etc/certs:ro
      - ./config.yaml:/etc/pterodactyl/config.yml
    working_dir: /var/lib/pterodactyl
    labels:
      - "traefik.enable=true"
      - "expose-external=true"
      - "traefik.http.routers.pterodactyl-daemon.entrypoints=websecure"
      - "traefik.http.routers.pterodactyl-daemon.rule=Host(`game-node2.hlresort.community`)"
      - "traefik.http.routers.pterodactyl-daemon-secure.entrypoints=websecure"
      - "traefik.http.routers.pterodactyl-daemon-secure.rule=Host(`game-node2.hlresort.community`)"
      - "traefik.http.routers.pterodactyl-daemon-secure.tls=true"
      - "traefik.http.routers.pterodactyl-daemon-secure.tls.certresolver=http"
      - "traefik.http.routers.pterodactyl-daemon-secure.service=pterodactyl-daemon"
      - "traefik.http.services.pterodactyl-daemon.loadbalancer.server.port=8080"
      - "traefik.docker.network=external"

networks:
    default:
        name: external
        external: true
