services:
  subscale: # https://tailscale.com/kb/1282/docker
    image: tailscale/tailscale:latest
    container_name: subscale
    hostname: subscale
    env_file: .env
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_HOSTNAME=futaba-docker-subnet
      - TS_ROUTES=172.21.0.0/16
      - TS_EXTRA_ARGS=--accept-routes --snat-subnet-routes=false 
    volumes:
      - /data/subscale/tailscale/var/lib/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

networks:
  default:
    name: tailscale
    external: true
