# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."hello-world-web" = {
    image = "nginx:latest";
    #    volumes = [ "${./nginx.conf}:/etc/nginx/conf.d/default.conf:rw" ];
    ports = [ "100.103.59.112:80:80/tcp" ];
    log-driver = "journald";
    extraOptions = [ "--network-alias=web" "--network=hello-world_default" ];
  };
  systemd.services."docker-hello-world-web" = {
    serviceConfig = { Restart = lib.mkOverride 90 "no"; };
    after = [ "docker-network-hello-world_default.service" ];
    requires = [ "docker-network-hello-world_default.service" ];
    partOf = [ "docker-compose-hello-world-root.target" ];
    wantedBy = [ "docker-compose-hello-world-root.target" ];
  };

  # Networks
  systemd.services."docker-network-hello-world_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f hello-world_default";
    };
    script = ''
      docker network inspect hello-world_default || docker network create hello-world_default
    '';
    partOf = [ "docker-compose-hello-world-root.target" ];
    wantedBy = [ "docker-compose-hello-world-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-hello-world-root" = {
    unitConfig = { Description = "Root target generated by compose2nix."; };
    wantedBy = [ "multi-user.target" ];
  };
}
