###
# Minimal Configuration File
#
# This configuration strips services to the absolute bare essentials to function.
# Very useful for reverse proxy configurations where a user would override networking anyways.
###
services:
  ##
  # -- Pterodactyl Daemon --
  # This service provides the wings runtime.
  ##
  daemon:
    environment:
      - TZ=${DAEMON_TIMEZONE:-UTC}
    image: docker.io/ccarney16/pterodactyl-daemon:${DAEMON_VERSION:-latest}
    ports:
      - 2023:2022
      - 8081:8080
    expose:
      - 8081
      - 2023
    privileged: true
    profiles: [ daemon ]
    restart: unless-stopped
    volumes:
      - /data/pterodactyl/var/lib/pterodactyl:/var/lib/pterodactyl
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/pterodactyl/:/tmp/pterodactyl/
      - /data/pterodactyl/conf.d/daemon:/etc/pterodactyl
      - ./conf.d/daemon/config.yml:/etc/pterodactyl/config.yml
      - ./conf.d/letsencrypt:/etc/letsencrypt:ro
      - ./conf.d/certs:/etc/certs:ro
    working_dir: ${DAEMON_DATA_DIRECTORY:-/var/lib/pterodactyl}
    labels:
      - "traefik.enable=true"
      - "expose-external=true"
      - "traefik.http.routers.pterodactyl-wing-secure.entrypoints=websecure"
      - "traefik.http.routers.pterodactyl-wing-secure.rule=Host(`node1.ptero.triserden.dev`)"
      - "traefik.http.routers.pterodactyl-wing-secure.tls=true"
      - "traefik.http.routers.pterodactyl-wing-secure.tls.certresolver=http"
      - "traefik.http.routers.pterodactyl-wing-secure.service=pterodactyl-wing"
      - "traefik.http.services.pterodactyl-wing-secure.loadbalancer.server.port=8081"
      - "traefik.http.middlewares.pterodactyl-wing-secure.headers.stsSeconds=315"
      - "traefik.http.middlewares.pterodactyl-wing-secure.headers.forceSTSHeader=false"
      - "traefik.http.middlewares.pterodactyl-wing-secure.headers.stsPreload=false"
      - "traefik.http.middlewares.pterodactyl-wing-secure.headers.stsIncludeSubdomains=false"
      - traefik.http.middlewares.secure-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*
      - traefik.http.routers.pterodactyl-wing-secure.middlewares=secure-headers,cors-headers
      - "traefik.docker.network=external"
    extra_hosts:
      - "ptero.triserden.dev:172.19.0.6"
  ##
  # -- MariaDB --
  # Required for the control panel to work.
  # Stores Server/User information
  ##
  mariadb:
    image: docker.io/library/mariadb:10.11
    env_file: ./conf.d/mariadb.env
    networks:
      default:
        aliases:
          - mysql
    profiles: [ panel ]
    restart: unless-stopped
    volumes:
      - /data/pterodactyl/data/mysql:/var/lib/mysql
  ##
  # -- Pterodactyl Panel --
  # This is the container that provides the main web interface.
  ##
  panel:
    env_file: ./conf.d/panel.env
    image: docker.io/ccarney16/pterodactyl-panel:${PANEL_VERSION:-latest}
    profiles: [ panel ]
    networks:
      default:
        ipv4_address: "172.19.0.6"
    restart: unless-stopped
    volumes:
      - /data/pterodactyl/data/panel:/data
    labels:
      - "traefik.enable=true"
      - "expose-external=true"
      - "traefik.http.routers.pterodactyl-panel-secure.entrypoints=websecure"
      - "traefik.http.routers.pterodactyl-panel-secure.rule=Host(`ptero.triserden.dev`)"
      - "traefik.http.routers.pterodactyl-panel-secure.tls=true"
      - "traefik.http.routers.pterodactyl-panel-secure.tls.certresolver=http"
      - "traefik.http.routers.pterodactyl-panel-secure.service=pterodactyl-panel"
      - "traefik.http.services.pterodactyl-panel.loadbalancer.server.port=80"
      - traefik.http.middlewares.secure-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.cors-headers.headers.accessControlAllowOriginList=*
      - traefik.http.routers.pterodactyl-panel-secure.middlewares=secure-headers,cors-headers
      - "traefik.http.middlewares.pterodactyl-panel-secure.headers.stsSeconds=315"
      - "traefik.http.middlewares.pterodactyl-panel-secure.headers.forceSTSHeader=false"
      - "traefik.http.middlewares.pterodactyl-panel-secure.headers.stsPreload=false"
      - "traefik.http.middlewares.pterodactyl-panel-secure.headers.stsIncludeSubdomains=false"
      - "traefik.docker.network=external"
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_started
  ##
  # -- Redis --
  ##
  redis:
    cpu_count: 2
    cpu_percent: 50
    image: docker.io/library/redis:alpine
    mem_limit: 128m
    networks:
      default:
        aliases:
          - cache
    profiles: [ panel ]
    restart: unless-stopped
networks:
    default:
        name: external
        external: true
