services: # https://github.com/pi-hole/docker-pi-hole/
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: 'Europe/Ansterdam'
      VIRTUAL_HOST: 'futaba'
    volumes:
      - '/data/pihole/etc/pihole:/etc/pihole'
      - '/data/pihole/etc/dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    network_mode: service:pihole-tailscale
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.routers.pihole.tls.certresolver=cloudflare"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.rule=Host(`pihole.local.triserden.dev`) && PathPrefix(`/admin`)"
      
      - "traefik.http.routers.pihole2.rule=Host(`pihole.local.triserden.dev`)"
      - traefik.http.middlewares.piholeredirect.redirectregex.regex=^https:\/\/([^\/]+)\/?(.*)$$
      - traefik.http.middlewares.piholeredirect.redirectregex.replacement=https://$${1}/admin/$${2}
      - "traefik.http.routers.pihole2.middlewares=piholeredirect"
        

  pihole-tailscale: # https://tailscale.com/kb/1282/docker
    image: tailscale/tailscale:latest
    container_name: pihole-tailscale
    hostname: pihole
    env_file: .env
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_HOSTNAME=pihole
    volumes:
      - /data/pihole/tailscale/var/lib/tailscale:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

networks:
  default:
    name: internal
    external: true
