# Auto-generated using compose2nix v0.3.1.
{ pkg, inputs, config, lib, ... }:

let secretsFolder = builtins.toString inputs.secrets;
in {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  sops.secrets."services/hlr_config.yaml" = {
    sopsFile =
      "${secretsFolder}/sops/${config.host.hostname}/services/hlr_config.yaml";
    format = "yaml";
    key = "";
  };
  # Containers
  virtualisation.oci-containers.containers."hlr_pterodactyl-daemon" = {
    image = "ccarney16/pterodactyl-daemon:latest";
    environment = { "TZ" = ''"Europe/Amsterdam"''; };
    volumes = [
      "/data/hlresort/conf.d/certs:/etc/certs:ro"
      "/data/hlresort/conf.d/daemon:/etc/pterodactyl:rw,Z"
      "/data/hlresort/conf.d/letsencrypt:/etc/letsencrypt:ro"
      "/data/hlresort/var/lib/pterodactyl:/data/hlresort/var/lib/pterodactyl:rw"
      "${
        config.sops.secrets."services/hlr_config.yaml".path
      }: /etc/pterodactyl/config.yml:r"
      "/tmp/pterodactyl/:/tmp/pterodactyl:rw,Z"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    ports = [ "2022:2022/tcp" "22565:22565/tcp" ];
    labels = {
      "traefik.docker.network" = "external";
      "traefik.enable" = "true";
      "traefik.http.routers.pterodactyl-daemon-secure.entrypoints" =
        "websecure";
      "traefik.http.routers.pterodactyl-daemon-secure.rule" =
        "Host(`game-node2.hlresort.community`)";
      "traefik.http.routers.pterodactyl-daemon-secure.service" =
        "pterodactyl-daemon";
      "traefik.http.routers.pterodactyl-daemon-secure.tls" = "true";
      "traefik.http.routers.pterodactyl-daemon-secure.tls.certresolver" =
        "http";
      "traefik.http.routers.pterodactyl-daemon.entrypoints" = "websecure";
      "traefik.http.routers.pterodactyl-daemon.rule" =
        "Host(`game-node2.hlresort.community`)";
      "traefik.http.services.pterodactyl-daemon.loadbalancer.server.port" =
        "8080";
    };
    log-driver = "journald";
    extraOptions = [ "--network-alias=daemon" "--network=external" ];
  };
  systemd.services."docker-hlr_pterodactyl-daemon" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [ "docker-compose-hlr_pterodactyl-root.target" ];
    wantedBy = [ "docker-compose-hlr_pterodactyl-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-hlr_pterodactyl-root" = {
    unitConfig = { Description = "Root target generated by compose2nix."; };
    wantedBy = [ "multi-user.target" ];
  };
}
