debug: ENC[AES256_GCM,data:Qfq4bwY=,iv:b7d3IqYNPowWzBD79Cu92svObNLJYguhzYxjN9THUA8=,tag:DPSJzHIij8ZmO0dfo8IjBg==,type:bool]
uuid: ENC[AES256_GCM,data:TPBBuHFx+7/W80PtsHe/eLtzGGbAauGuObH9dlFRl0A/YDCD,iv:V/7DNZqWetLJ84IKhOT9jPLo8gGQkbVwdZeh2V3beYY=,tag:hll9pbGgYDxFbjadA2vQlg==,type:str]
token_id: ENC[AES256_GCM,data:9cQAn+gIOOe09pvHNXOq3Q==,iv:beqgLwmzS0ogwARSYSMNKoEumrTdXuina0vB+46t1N4=,tag:kcuHF+aF5d8qs2mE/qV4eg==,type:str]
token: ENC[AES256_GCM,data:Ya6nmayD/81+tyKZXtRfiSlofJO8RktI2iPzdr09DDGnu1UCtwyY9k2v76ac1bZ01EEGqdrY/8pTIDzVrVHZcA==,iv:4DMTxTSaPCDRRv6RgWA9j0nhtganbXDIQUn1aoeB7yY=,tag:ERFznRstWBzvj/uGBrAVNw==,type:str]
api:
    host: ENC[AES256_GCM,data:H9IeVczMaA==,iv:9Qm1cb/3Bve6+BLyfZ+qDSfmTbWfA918rBBi413gm1U=,tag:SFiqJkACWy3xA4pm3Ce+ww==,type:str]
    port: ENC[AES256_GCM,data:DL+Ycw==,iv:PTfVDA0uY8lWRSnjJzySIs6UKjSqlsWj815irKQan80=,tag:/j5t/Or3zelN8XvnV929uQ==,type:int]
    ssl:
        enabled: ENC[AES256_GCM,data:AVNmqg==,iv:f2EnVuxGbF5rSPErbMpjtMOUo4Ndz6m47vZ2fi09K2I=,tag:sniukbMVV0QZY3CqrDWc+Q==,type:bool]
        cert: ENC[AES256_GCM,data:xonRDiTrxgIrJYNUVrt5miMlCNXs/l2ggVu3nlyZZmHEiwdDTY4Auag=,iv:eadKT/LaW0RlPwa/o9ix1Fw5lTCQ9G2z4JBBNYhqQtQ=,tag:qZh3Md/Z+A8njUkXE3gegA==,type:str]
        key: ENC[AES256_GCM,data:cV+7Pwh1BskcDWLJLCvr/psVIWis49CvkXtejhbfSBjhyfnO+iOA,iv:cceCutqmoujrd/wk4wsE7M3Fw+zdMD5CZ3ZWSKZy4ng=,tag:vzulBgfHMm5Zu7lSZpWB7w==,type:str]
    upload_limit: ENC[AES256_GCM,data:TIFt,iv:sfE6IckQhPYRVOp/Ey10XN5IUOcPhVPS0QOPa0t9hLQ=,tag:Fwc8msAkMnM2FFXxXLWqVA==,type:int]
system:
    data: ENC[AES256_GCM,data:kb3DhSRivoKtnpxTFgi2jd3OssnFJ8qu1W04rg==,iv:pWlIgUltHdAHUXDc6SQIVHGSxvrqdu5DF3Kek0dkOl4=,tag:TBvthOUMNdd02XiL6qrvXA==,type:str]
    sftp:
        bind_port: ENC[AES256_GCM,data:MwdJfw==,iv:HXMNO0pINTKmPYxdXauyzDoNjD9IupaXKTvlHPBfyDE=,tag:7wlpx1xom/KOBd8mbuLUqA==,type:int]
allowed_mounts: []
remote: ENC[AES256_GCM,data:qSnZykv7f2y13rFDdUU2D8ibEiWgdZ3L2pkjlpUjikxU+cFTROf0,iv:9urkOLjTB+ys2qmYA2D112q8jOfURP2m4cP5e6F6QMg=,tag:CVhH5t1ZIBGn0XH6PIq9Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15qwcm0rtksf2yqm2wqxawrex49cllp77tuayvn4yq9ufk44l9adsdyzk79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z1NRekNibGJzN203bC81
            eU9SRFEvV1VoTjdqMCtwNEM2TGVFOVoweEdRCmZWTG96SE9GbTM5dGl1WmtrUGM5
            OHRITkR4NDJ4WUJZb1l1dEM5bmtMa0kKLS0tIDR4cllGK3lIQWxnQzlaSkVDL0pu
            ZWNhUHBZeFNWSnFQWGR3THhjRit3S1UKbNiJGUtFUIG3i3ncKlC2xOo0yC4T9/ua
            IzeFPpf+UqUrf8ZP3cE0zavB8AXG/VF4anuOpJaQBVvKeScPtAHMCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-08T20:14:34Z"
    mac: ENC[AES256_GCM,data:bdxjzZYFeNoPeAFnwuUoS8ysykmwfyaEYoPFBkQq9K430nT2mXlJEpOavHTsE5J4Tl1sLEtSH5G35NkQhQfVgtbL3M6680SBm6RloOWq4L/dSI3AvQrb/30xyXeOyiob3zacGuQYTrXNZWygYltbyt5Gm/yJMaiO00Iv+NLsAD4=,iv:wk1Ubgjsz8w00ja7Q1mcC3ZUaru7un1/YUohk1SSn2U=,tag:MF644gdChb3wxCJue43xkQ==,type:str]
    pgp:
        - created_at: "2025-01-08T15:07:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DMGicT/uUkIcSAQdAwNPesPX0LGHI3jAyMonzvnB7zpr03d8U2yPyU32zq0Iw
            lzLWVWF91tZZbTEVPrU4XQuvzTaNC9rOQdKkEzC5082AZKh1mATJf6ljzgnKPIJz
            0l4BE0F85ItiW1w/hAQfwgvO9xMEQGd0BUR7Ed9Clv8zK8EmUZgdgU60L3rq6abb
            O+/1PUrlC/UUsiyhGp+KbVeWFB09nRIRPnuvIJOVIX/RUespLKxF0OkOeTBwY+zK
            =kmIm
            -----END PGP MESSAGE-----
          fp: 2422C7EE03C629FD998BF923FD5CD86B6562D6B7
    unencrypted_suffix: _unencrypted
    version: 3.9.2
