debug: ENC[AES256_GCM,data:Qfq4bwY=,iv:b7d3IqYNPowWzBD79Cu92svObNLJYguhzYxjN9THUA8=,tag:DPSJzHIij8ZmO0dfo8IjBg==,type:bool]
uuid: ENC[AES256_GCM,data:seCa/Uu5RraDRXolIZbqkcfZrebYbxUaXUacScj6AQc+atYp,iv:8JPcUL5TUHl3SkyqkcP10H0Lz/YmOwuhZlC/N+j6ky8=,tag:Z3Wv3mHNTI1SQu3leujHrw==,type:str]
token_id: ENC[AES256_GCM,data:kCHf/3CBZKCcIUvlUDwXbA==,iv:yf4+Cpgvp/UImyNe2DH3VVm18peYqLBJtRGHoqDojwk=,tag:Yratwcfo6a0dy7/6xWMsjA==,type:str]
token: ENC[AES256_GCM,data:KvsydVUZfUvrwHXdaLaQl3LQ7K5FJf8Lfekyzng8ZlIGF2kl2qK5jB6LPNkJig5lgy+JlAkBMsLT3udTGMWHHA==,iv:2wte+CQ4q6MTQm9CaZowGjcy4k2KJiAOv1D8xSYfsoQ=,tag:xar5xGMcVjvVnaU3D4ChnQ==,type:str]
api:
    host: ENC[AES256_GCM,data:H9IeVczMaA==,iv:9Qm1cb/3Bve6+BLyfZ+qDSfmTbWfA918rBBi413gm1U=,tag:SFiqJkACWy3xA4pm3Ce+ww==,type:str]
    port: ENC[AES256_GCM,data:MBmsDg==,iv:+ajkBPeDcOTqD2pTSYCYxDRHrtCazUmwfO+7luphifg=,tag:cHXfEjm++2jDNduOv4O+Pw==,type:int]
    ssl:
        enabled: ENC[AES256_GCM,data:N2lPDpg=,iv:SypjmLyTb9/VUtdosW3k40DoWqBXN0x52e/rdNstV38=,tag:p0jcDD3uH6NAqxYcMBjYXQ==,type:bool]
        cert: ENC[AES256_GCM,data:Ed7HrJAJvHffcszF2V023zURA87bnY8TOCYLWNmjCYfc8A/tBaa2o2Z/HvWp6amfWNDI8DZCk6g12x0qC9L15uDJQQ==,iv:ZtqiPndMXZcYTU71hpiwghyzY34zRieMFfbRy4QQEao=,tag:MoINr1xAotffgn1/PyU8bQ==,type:str]
        key: ENC[AES256_GCM,data:oJ9njQnNDdv7l0k7MRIByCK1VQlzskTP1B3bbOQQgSmeQWC/PdNL+rniCEJGfHyqp5A482jHVbIf7NUg7d5+zTk=,iv:ij0goWC2ilKv68q1YrKTDsmc6aTkR/Weujb6gSpR4Ts=,tag:VJ9Pq8ccjxw4bDB/SCrjRw==,type:str]
    upload_limit: ENC[AES256_GCM,data:TIFt,iv:sfE6IckQhPYRVOp/Ey10XN5IUOcPhVPS0QOPa0t9hLQ=,tag:Fwc8msAkMnM2FFXxXLWqVA==,type:int]
system:
    data: ENC[AES256_GCM,data:kb3DhSRivoKtnpxTFgi2jd3OssnFJ8qu1W04rg==,iv:pWlIgUltHdAHUXDc6SQIVHGSxvrqdu5DF3Kek0dkOl4=,tag:TBvthOUMNdd02XiL6qrvXA==,type:str]
    sftp:
        bind_port: ENC[AES256_GCM,data:B+XpWQ==,iv:qclzhGDjuTPf1NGXIcJDj+/89ap5A5Jle/rgdlKdT90=,tag:ntUSjnR25b/Cesb99TwJNg==,type:int]
allowed_mounts: []
remote: ENC[AES256_GCM,data:qXIADQNtOvEiO4oQpwNvCtPSqBvdnrLHsaGFnHfRwxN1,iv:a30iC7J7f11RIIpNWw0ftiswjY7F8GpNyt6bqs3mWa4=,tag:+8P8wpX2cx7xc80RO/f6FQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15qwcm0rtksf2yqm2wqxawrex49cllp77tuayvn4yq9ufk44l9adsdyzk79
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5Z1NRekNibGJzN203bC81
            eU9SRFEvV1VoTjdqMCtwNEM2TGVFOVoweEdRCmZWTG96SE9GbTM5dGl1WmtrUGM5
            OHRITkR4NDJ4WUJZb1l1dEM5bmtMa0kKLS0tIDR4cllGK3lIQWxnQzlaSkVDL0pu
            ZWNhUHBZeFNWSnFQWGR3THhjRit3S1UKbNiJGUtFUIG3i3ncKlC2xOo0yC4T9/ua
            IzeFPpf+UqUrf8ZP3cE0zavB8AXG/VF4anuOpJaQBVvKeScPtAHMCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-08T23:32:50Z"
    mac: ENC[AES256_GCM,data:J3KnJFb3xaZWnij6V5DnzrPIvfNj16jgkIY65+9zQ936rz4N3V1cqLPJHYJTotlRd+ywUfm35nEHi+/wV08de8K13RY3ikYzZeiFEtKu9XLFBLEfRliRItd1aoEf1qAUA0egx2JYl3YPSuJx2F655af/E3/Nqy306ihfVVSv924=,iv:m3E7T/zuDGQunT00VlgJf0E33k6Gu1XJGBod+s/DDn0=,tag:kGrYE2O8i1JoO0aJILnAVA==,type:str]
    pgp:
        - created_at: "2025-01-08T15:07:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DMGicT/uUkIcSAQdAwNPesPX0LGHI3jAyMonzvnB7zpr03d8U2yPyU32zq0Iw
            lzLWVWF91tZZbTEVPrU4XQuvzTaNC9rOQdKkEzC5082AZKh1mATJf6ljzgnKPIJz
            0l4BE0F85ItiW1w/hAQfwgvO9xMEQGd0BUR7Ed9Clv8zK8EmUZgdgU60L3rq6abb
            O+/1PUrlC/UUsiyhGp+KbVeWFB09nRIRPnuvIJOVIX/RUespLKxF0OkOeTBwY+zK
            =kmIm
            -----END PGP MESSAGE-----
          fp: 2422C7EE03C629FD998BF923FD5CD86B6562D6B7
    unencrypted_suffix: _unencrypted
    version: 3.9.2
